version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2019
nuget:
  disable_publish_on_pr: true
install:
  - git submodule update --init --recursive
build_script:
- cmd: >-
    .\psake.cmd ci

    7z a FaasNetCLI.zip .\build\results\cli\*
test: off
artifacts:
- path: FaasNetCLI.zip
  name: FaasNetCli
- path: build\results\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/advance-ict/api/v2/package
  api_key:
    secure: zs1JVjFHRdvB36fGq2rN8MR7QeJnCVkt7VTG4ZHT5OYDNpuh2AlGHqK+rseevn8l
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
- provider: NuGet
  name: production
  artifact: /.*\.nupkg/
  api_key:
    secure: ppwdCVQ3Ue4Msodk0VafBwlpujkDBddjGg7okIRojYiVFhVD6fhd7ERijm3RzSGD
  on:
    branch: master
    appveyor_repo_tag: true
- provider: GitHub
  auth_token:
    secure: zTfwwuXIaZPeCrcbsQhuJxmDiIoya4VeC+GZZVv0+SSwX0oIPgYdkiVLxKjFqbEy
  artifact: FaasNetCli
  on:
    branch: master
    appveyor_repo_tag: true