apiVersion: v1
kind: Service
metadata:
  name: faas-kubernetes-entry
spec:
  type: NodePort
  selector:
    run: faas-kubernetes
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001