apiVersion: v1
kind: Service
metadata:
  name: faas-website-externalentry
spec:
  type: NodePort
  selector:
    run: faas-website
  ports:
  - port: 4200
    protocol: TCP
    targetPort: 4200
    nodePort: {{ .Values.website.nodePort }}