apiVersion: v1
kind: Service
metadata:
  name: faas-gateway-entry
spec:
  type: NodePort
  selector:
    run: faas-gateway
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: {{ .Values.gateway.nodePort }}