apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-website
spec:
  selector:
    matchLabels:
      run: faas-website
  replicas: {{ .Values.website.replicaCount }}
  template:
    metadata:
      labels:
        run: faas-website
    spec:
      containers:
      - name: faas-website
        image: "{{ .Values.website.image }}:{{ .Values.website.tag }}"
        ports:
        - containerPort: 4200
