apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-prometheus
spec:
  selector:
    matchLabels:
      run: faas-prometheus
  replicas: {{ .Values.gateway.replicaCount }}
  template:
    metadata:
      labels:
        run: faas-prometheus
    spec:
      volumes:
      - name: prometheus-pv-storage
        persistentVolumeClaim:
          claimName: prometheus-pv-claim
      containers:
      - name: faas-website
        image: "{{ .Values.prometheus.image }}:{{ .Values.prometheus.tag }}"
        ports:
        - containerPort: 9090
        volumeMounts:
        - mountPath: "/shared"
          name: prometheus-pv-storage
