apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-kubernetes
spec:
  selector:
    matchLabels:
      run: faas-kubernetes
  replicas: {{ .Values.kubernetes.replicaCount }}
  template:
    metadata:
      labels:
        run: faas-kubernetes
    spec:
      containers:
      - name: faas-kubernetes
        image: "{{ .Values.kubernetes.image }}:{{ .Values.kubernetes.tag }}"
        ports:
        - containerPort: 8080
