apiVersion: v1
entries:
  faasnet:
  - apiVersion: v1
    appVersion: 0.0.3
    created: "2021-10-13T20:59:19.987527+02:00"
    description: A helm chart to install faasnet
    digest: cd38c6385ed0a50366db523e6ff1ce9d27d0ff9086c0b32c01298daa25c51321
    home: https://github.com/simpleidserver/FaasNet
    maintainers:
    - email: agentsimpleidserver@gmail.com
      name: SimpleIdServer
    name: faasnet
    urls:
    - faasnet-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v1
    appVersion: 0.0.1
    created: "2021-10-13T20:59:19.987527+02:00"
    description: A helm chart to install faasnet
    digest: f026cd42897393607222fdb81cb1cd1c115ddb2f2a70099142d5f3266d23b678
    home: https://github.com/simpleidserver/FaasNet
    maintainers:
    - email: agentsimpleidserver@gmail.com
      name: SimpleIdServer
    name: faasnet
    urls:
    - faasnet-0.0.1.tgz
    version: 0.0.1
generated: "2021-10-13T20:59:19.9858952+02:00"
