apiVersion: v1
kind: Service
metadata:
  name: faas-prometheus-entry
spec:
  type: NodePort
  selector:
    run: faas-prometheus
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30004