# Install https://www.elastic.co/fr/downloads/elastic-cloud-kubernetes
apiVersion: v1
kind: Namespace
metadata:
  name: faas
---
kind: Service
apiVersion: v1
metadata:
  name: quickstart-es-external
  labels:
    component: elasticsearch
spec:
  type: NodePort
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: quickstart
  ports:
  - name: 'https'
    protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 30070
  - name: 'tls-transport'
    protocol: TCP
    port: 9300
    targetPort: 9300
    nodePort: 30071
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.1.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false