apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-gateway
spec:
  selector:
    matchLabels:
      run: faas-gateway
  replicas: 1
  template:
    metadata:
      labels:
        run: faas-gateway
    spec:
      volumes:
      - name: prometheus-pv-storage
        persistentVolumeClaim:
          claimName: prometheus-pv-claim
      containers:
      - name: faas-gateway
        image: localhost:5000/faasgateway
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/shared"
          name: prometheus-pv-storage
