apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-prometheus
spec:
  selector:
    matchLabels:
      run: faas-prometheus
  replicas: 1
  template:
    metadata:
      labels:
        run: faas-prometheus
    spec:
      containers:
      - name: faas-website
        image: localhost:5000/faasprometheus
        ports:
        - containerPort: 9090
